name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -sSf https://sh.rustup.rs | sh -s -- -y

      # rust
      - run: cargo build
      - run: cargo check
      - run: cargo test

      # wasm
      - run: cargo install wasm-pack
      - run: wasm-pack build
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -sSf https://sh.rustup.rs | sh -s -- -y
      - run: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

      # wasm
      - run: cargo install wasm-pack
      - run: wasm-pack build

      # js
      - run: npm ci
