name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -sSf https://sh.rustup.rs | sh -s -- -y
      - run: cargo build
      - run: cargo check
      - run: cargo test
      - run: pip install tomlq
      - run: cargo install wasm-pack --version $(tomlq -r '.package[] | select(.name == "wasm-pack") .version' Cargo.lock)
      - run: wasm-pack build --target web
