name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # rust
      - run: cargo build
      - run: cargo check
      - run: cargo test

      # wasm
      - run: cargo install wasm-pack
      - run: sudo apt-get update && sudo apt-get install -y binaryen
      - run: wasm-pack build
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # wasm
      - run: cargo install wasm-pack
      - run: sudo apt-get update && sudo apt-get install -y binaryen
      - run: wasm-pack build

      # js
      - run: npm ci
      - run: npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: [rust, js]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: cargo install wasm-pack
      - run: sudo apt-get update && sudo apt-get install -y binaryen
      - run: wasm-pack build

      - run: npm ci
      - run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        env:
          CI: "true"
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
