name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://www.rust-lang.org/tools/install
      - run: curl -sSf https://sh.rustup.rs | sh
      - run: cargo build
